logging:
  level:
    com.gateway: DEBUG

server:
  port: 8200

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://tori-story.com:8201
          predicates:
            - Path=/member/**
        - id: challenge-service
          uri: http://tori-story.com:8202
          filters:
            - AuthFilter
          predicates:
            - Path=/challenge/**
        - id: tori-service
          uri: http://tori-story.com:8203
          filters:
            - AuthFilter
          predicates:
            - Path=/tori/**
