pipeline {
    agent any

    tools {
		nodejs "nodejs"
	}

    stages {
        // React 빌드 스테이지: React 프로젝트를 빌드합니다.
        stage('React Build') {
          steps {
            dir('frontend/tori-story') {
                sh 'npm i -g pnpm'
                        sh 'rm -rf pnpm-lock.yaml'
              sh 'pnpm install'
              sh 'NODE_OPTIONS=--max-old-space-size=4096 pnpm build'
            }
          }
		}

        // Docker 이미지 빌드 스테이지: Dockerfile을 기반으로 이미지를 빌드합니다.
		stage('Docker Build') {
        steps {
          dir('frontend/tori-story') {
            sh 'docker build -t toristory-frontend:latest .'
          }
        }
		}

        // 배포 스테이지: 이전에 실행 중인 컨테이너를 제거하고 새로운 이미지로 컨테이너를 실행합니다.
        stage('Deploy') {
            steps {
                // 실행 중인 컨테이너 제거
                sh 'docker rm -f front'

                // 새로운 이미지로 컨테이너를 백그라운드에서 실행
			        	sh 'docker run -d --name front -p 3126:3126 -e TZ=Asia/Seoul -u root toristory-frontend:latest'
            }
        }

        // 완료 스테이지: 더이상 사용되지 않는 Docker 이미지를 제거합니다.
        stage('Finish') {
            steps {
                // 사용되지 않는 (dangling) 이미지를 찾아 제거합니다.
                sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
            }
        }
    }
}

